---
title: "Professional Experience"
output: 
  html_document:
    toc: true
    toc_float: true
---

## EDUCATION BACKGROUND

**<font size="4"> Columbia University** (Sep 2022 - Present)

Master of Science in Biostatistics, Mailman School of Public Health

**<font size="4"> University of Michigan, Ann Arbor</font>**              (Dec 2019 - May 2022)                                              
Mathematical Science & Statistics Bachelor, College of Literature, Science and the Arts 

**Cumulative GPA**: 3.73/4.00       **Major GPA**: 3.84/4.00

*Relevant Coursework*:   
*Linear Algebra, Applied Modern Algebra, Differential Equation, Advance Calculus, Numerical Methods, Mathematical Modeling in Biology, Introduction to Statistics and Data Analysis, Probability, Theory Statistics, Elementary Programming, Statistical Computing, Data Mining, Genetics, Human Physiology, Sciences of Medicines*

**<font size="4"> University of North Carolina, Chapel Hill</font>**       (Aug 2018 - Apr 2019)

Biology Bachelor, College of Literature, Arts and Sciences 

**Cumulative GPA**: 3.83/4.00

*Relevant Coursework*:  
*Multivariable Calculus, General Chemistry, Chemistry Principle and Application, Introduction of Biology*

## RESEARCH EXPERIENCES

**<font size="4"> Yale University, Public Health and Biostatistics Research</font>** (July - Sep 2021)

*Trainee and Project Member*

-	Researched cancer data, survival analysis and public health under the close guidance in project course works and team projects with professor Shuangge Ma at Yale University.
-	Conducted Data Analysis on betel quid and its relationship between the risk of oral cancer.
-	Effectively applied different sorts of data analytics tools and applications to complete assignments and research.
-	Drafted research reports, lab reports and stage progress reports along with the team on a regular basis.
-	Completed literature review and journal articles purview over a dozen of academic journals, periodicals and e-files.
-	Joined meeting with professor, supervisor and team mates to discuss progress and modifications of research works. 

**<font size="4"> Johns Hopkins University, Online Public Health Research Program</font>** (Aug 2020 - Nov 2020)

*Member*

-	Researched genetics, precision public health, and disease prevention.
-	Conducted rigorous training on data analytics skills (R programming).
-	Prepared paper (Comparison between SARS-CoV and SARS-CoV2) published on ICBB2021 conf.

**<font size="4"> University of Michigan Pre-Pharmacy Association</font>** (Dec 2019 - May 2020)

*Member*

-	Provided support on blood drives, pharmacy flu clinics, and pharmacy group panels
-	Shadowed doctors at University of Michigan Campus Hospital. 

**<font size="4"> Ornithological Lab at Shaanxi Normal University </font>** (Jun 2017 - Aug 2019)

*Junior Investigator*

-	In-depth study on photoreceptors and circadian rhythm in birds' systems.
-	Analysis of photopigment distribution and laboratory dissection of avian brains.
-	First writer of the research abstract, prepared paper published at ISIZ conf.

## CAMPUS ACTIVITIES 

**<font size="4"> University of Michigan, Mathematics Department </font>** (Sep 2021- Dec 2021)

*Teaching Assistant*

-	Guided and graded students’ assignments and coursework weekly on applied modern algebra and abstract algebra.
-	Provided support and feedback for the course instructor weekly.

**<font size="4"> University of Michigan Chinese Scholar and Student Association </font>** (Dec 2019 - Dec 2020)

*Member*

-	Provided support for activities hosted by the student association, such as Lunar New Year Party and Christmas Party
- Responsible for the daily promotion of the association

